### ISSUE TITLE
Remove formatting

### ISSUE THREAD

**Issue by Orbycius** [inossidabile/wash_out#162]
The XML returned via washout is nicely formatted, but we'd like it compressed for sending over the wire. Can we turn off the formatting so it's just one big long line?

Thanks

**Comment by inossidabile** [comment]
We are using internal Rails rendering based on `XMLBuilder`. I couldn't find a way to tell Rails not to beautify the output when it's used as a built-in renderer. I would accept pull-request modifying the behavior of `dispatcher.rb` in `#_render_soap` that would use `render :text` with direct usage of `XMLBuilder` instead of relying on Rails. I won't do it myself tho.
