### ISSUE TITLE
Support Rails 4.2

### ISSUE THREAD

**Issue by badlamer** [inossidabile/wash_out#168]
Error in routes.rb when starts rails 4.2 application.

```
! Unable to load application: TypeError: no implicit conversion of ActionDispatch::Routing::Mapper::Scope into Hash
/home/badlamer/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/core_ext/hash/reverse_merge.rb:19:in `merge!': no implicit conversion of ActionDispatch::Routing::Mapper::Scope into Hash (TypeError)
```

**Comment by cbarratt** [comment]
Also encountering this issue after upgrading to Rails 4.2 - struggling to figure out a fix

**Comment by lojza1** [comment]
Encountering this issue too, please help

**Comment by tahanson** [comment]
I believe the fix for this issue breaks namespaced wash_out routes. The resulting controller name does not include the namespace.
Example:
```
namespace :apis do
  wash_out :asdf
end
```
When running rake routes, the controller name is AsdfController but should be Apis::AsdfController

2 possible work arounds...
```
namespace :apis do
  wash_out :asdf, module: 'apis'
end
```
or 
```
namespace :apis do
end
wash_out 'apis/asdf'
```

I'm not sure exactly what the fix should be. Looking at these two lines in the dispatcher...
```
       options.each_with_index { |key, value|  @scope[key] = value } if @scope
       controller_class_name = [options[:module], controller_name].compact.join("/")
```
Should the second line use @scope[:module] instead of options[:module]?
