### ISSUE TITLE
`dateTime`s not in the correct format

### ISSUE THREAD

**Issue by Mange** [inossidabile/wash_out#202]
I get this output:
```xml
<created_at xsi:type="xsd:dateTime">2016-04-29 13:21:41 +0200</created_at>
```

Expected output:
```xml
<created_at xsi:type="xsd:dateTime">2016-04-29T13:21:41+0200</created_at>
```

---

Seems like the output helper just uses implicit `to_s` of the Ruby type, which isn't valid ISO8601. `Time`s should use `xmlschema` to get the proper format. I might just've misread the code, however. Please advice.

**Comment by yjukaku** [comment]
Just wondering, is the standard to always use ISO8601, or is there a way to check what output format is expected for dateTime?

**Comment by Mange** [comment]
Here's a reference I found:

[xsd:dateTime, Datatype Reference](http://books.xmlschemata.org/relaxng/ch19-77049.html), *RELAX NG* by Eric van der Vlist, published by O'Reilly & Associates (ISBN: 0596004214)

**Comment by inossidabile** [comment]
Use `DateTime` to not have the issue.

**Comment by inossidabile** [comment]
So after playing with it around a bit I decided that it won't be fixed. I understand that technically it might look like a bug but I see it as implementation specific ;). WashOut doesn't override the textual representation of returned data and lets you handle it. Since we have `DateTime` and you can easily achieve proper output I don't see the need to force it. The other day you might put integer in there and it will still let you do that. We either change this strategy completely or keep it. And I'd rather keep it.
